#!/bin/sh
export PATH=/usr/local/bin:$PATH
cd /space/git/rundmc.git/setup
./optimize-js.sh

# Enable the following once we merge the apidoc branch to master
cd /space/git/rundmc.git/apidoc/setup
./optimize-js.sh
