#!/bin/sh
cd ..
export GIT_DIR=".git"
git checkout -f
export PATH=/usr/local/bin:$PATH
cd /space/git/rundmc.git/src/setup
./optimize-js.sh

# Enable the following once we merge the apidoc branch to master
cd /space/git/rundmc.git/src/apidoc/setup
./optimize-js.sh
